// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetANC() {
  return window['go']['main']['App']['GetANC']();
}

export function GetBattery() {
  return window['go']['main']['App']['GetBattery']();
}

export function GetCachedDevices() {
  return window['go']['main']['App']['GetCachedDevices']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ScanDevices() {
  return window['go']['main']['App']['ScanDevices']();
}

export function SetANC(arg1) {
  return window['go']['main']['App']['SetANC'](arg1);
}

export function SetEQ(arg1) {
  return window['go']['main']['App']['SetEQ'](arg1);
}
