// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetANC():Promise<string>;

export function GetBattery():Promise<number>;

export function GetInfo():Promise<main.DeviceInfo>;

export function IsConnected():Promise<boolean>;

export function SetANC(arg1:string):Promise<void>;

export function SetEQ(arg1:string):Promise<void>;
